export const ICONS = [
	{
		id: 'hmg_emplacement',
		label: 'HMG Emplacement',
		group_id: 'bridge',
		filename: 'hmg_emplacement',
	},
	{
		id: 'orbital_ems_strike',
		label: 'Orbital EMS Strike',
		group_id: 'bridge',
		filename: 'orbital_ems_strike',
	},
	{
		id: 'orbital_gas_strike',
		label: 'Orbital Gas Strike',
		group_id: 'bridge',
		filename: 'orbital_gas_strike',
	},
	{
		id: 'orbital_precision_strike',
		label: 'Orbital Precision Strike',
		group_id: 'bridge',
		filename: 'orbital_precision_strike',
	},
	{
		id: 'orbital_smoke_strike',
		label: 'Orbital Smoke Strike',
		group_id: 'bridge',
		filename: 'orbital_smoke_strike',
	},
	{
		id: 'shield_generator_relay',
		label: 'Shield Generator Relay',
		group_id: 'bridge',
		filename: 'shield_generator_relay',
	},
	{
		id: 'tesla_tower',
		label: 'Tesla Tower',
		group_id: 'bridge',
		filename: 'tesla_tower',
	},
	{
		id: 'anti-personnel_minefield',
		label: 'Anti-Personnel Minefield',
		group_id: 'engineering_bay',
		filename: 'anti-personnel_minefield',
	},
	{
		id: 'arc_thrower',
		label: 'Arc Thrower',
		group_id: 'engineering_bay',
		filename: 'arc_thrower',
	},
	{
		id: 'ballistic_shield_backpack',
		label: 'Ballistic Shield Backpack',
		group_id: 'engineering_bay',
		filename: 'ballistic_shield_backpack',
	},
	{
		id: 'grenade_launcher',
		label: 'Grenade Launcher',
		group_id: 'engineering_bay',
		filename: 'grenade_launcher',
	},
	{
		id: 'guard_dog_rover',
		label: 'Guard Dog Rover',
		group_id: 'engineering_bay',
		filename: 'guard_dog_rover',
	},
	{
		id: 'incendiary_mines',
		label: 'Incendiary Mines',
		group_id: 'engineering_bay',
		filename: 'incendiary_mines',
	},
	{
		id: 'laser_cannon',
		label: 'Laser Cannon',
		group_id: 'engineering_bay',
		filename: 'laser_cannon',
	},
	{
		id: 'shield_generator_pack',
		label: 'Shield Generator Pack',
		group_id: 'engineering_bay',
		filename: 'shield_generator_pack',
	},
	{
		id: 'supply_pack',
		label: 'Supply Pack',
		group_id: 'engineering_bay',
		filename: 'supply_pack',
	},
	{
		id: 'hellbomb',
		label: 'Hellbomb',
		group_id: 'general_stratagems',
		filename: 'hellbomb',
	},
	{
		id: 'orbital_illumination_flare',
		label: 'Orbital Illumination Flare',
		group_id: 'general_stratagems',
		filename: 'orbital_illumination_flare',
	},
	{
		id: 'prospecting_drill',
		label: 'Prospecting Drill',
		group_id: 'general_stratagems',
		filename: 'prospecting_drill',
	},
	{
		id: 'reinforce',
		label: 'Reinforce',
		group_id: 'general_stratagems',
		filename: 'reinforce',
	},
	{
		id: 'resupply',
		label: 'Resupply',
		group_id: 'general_stratagems',
		filename: 'resupply',
	},
	{
		id: 'seaf_artillery',
		label: 'SEAF Artillery',
		group_id: 'general_stratagems',
		filename: 'seaf_artillery',
	},
	{
		id: 'seismic_probe',
		label: 'Seismic Probe',
		group_id: 'general_stratagems',
		filename: 'seismic_probe',
	},
	{
		id: 'sos_beacon',
		label: 'SOS Beacon',
		group_id: 'general_stratagems',
		filename: 'sos_beacon',
	},
	{
		id: 'super_earth_flag',
		label: 'Super Earth Flag',
		group_id: 'general_stratagems',
		filename: 'super_earth_flag',
	},
	{
		id: 'upload_data',
		label: 'Upload Data',
		group_id: 'general_stratagems',
		filename: 'upload_data',
	},
	{
		id: 'eagle_110mm_rocket_pods',
		label: 'Eagle 110MM Rocket Pods',
		group_id: 'hangar',
		filename: 'eagle_110mm_rocket_pods',
	},
	{
		id: 'eagle_500kg_bomb',
		label: 'Eagle 500KG Bomb',
		group_id: 'hangar',
		filename: 'eagle_500kg_bomb',
	},
	{
		id: 'eagle_airstrike',
		label: 'Eagle Airstrike',
		group_id: 'hangar',
		filename: 'eagle_airstrike',
	},
	{
		id: 'eagle_cluster_bomb',
		label: 'Eagle Cluster Bomb',
		group_id: 'hangar',
		filename: 'eagle_cluster_bomb',
	},
	{
		id: 'eagle_napalm_airstrike',
		label: 'Eagle Napalm Airstrike',
		group_id: 'hangar',
		filename: 'eagle_napalm_airstrike',
	},
	{
		id: 'eagle_rearm',
		label: 'Eagle Rearm',
		group_id: 'hangar',
		filename: 'eagle_rearm',
	},
	{
		id: 'eagle_smoke_strike',
		label: 'Eagle Smoke Strike',
		group_id: 'hangar',
		filename: 'eagle_smoke_strike',
	},
	{
		id: 'eagle_strafing_run',
		label: 'Eagle Strafing Run',
		group_id: 'hangar',
		filename: 'eagle_strafing_run',
	},
	{
		id: 'jump_pack',
		label: 'Jump Pack',
		group_id: 'hangar',
		filename: 'jump_pack',
	},
	{
		id: 'orbital_120mm_he_barrage',
		label: 'Orbital 120MM HE Barrage',
		group_id: 'orbital_cannons',
		filename: 'orbital_120mm_he_barrage',
	},
	{
		id: 'orbital_380mm_he_barrage',
		label: 'Orbital 380MM HE Barrage',
		group_id: 'orbital_cannons',
		filename: 'orbital_380mm_he_barrage',
	},
	{
		id: 'orbital_airburst_strike',
		label: 'Orbital Airburst Strike',
		group_id: 'orbital_cannons',
		filename: 'orbital_airburst_strike',
	},
	{
		id: 'orbital_gatling_barrage',
		label: 'Orbital Gatling Barrage',
		group_id: 'orbital_cannons',
		filename: 'orbital_gatling_barrage',
	},
	{
		id: 'orbital_laser',
		label: 'Orbital Laser',
		group_id: 'orbital_cannons',
		filename: 'orbital_laser',
	},
	{
		id: 'orbital_railcannon_strike',
		label: 'Orbital Railcannon Strike',
		group_id: 'orbital_cannons',
		filename: 'orbital_railcannon_strike',
	},
	{
		id: 'orbital_walking_barrage',
		label: 'Orbital Walking Barrage',
		group_id: 'orbital_cannons',
		filename: 'orbital_walking_barrage',
	},
	{
		id: 'anti-materiel_rifle',
		label: 'Anti-Materiel Rifle',
		group_id: 'patriotic_administration_center',
		filename: 'anti-materiel_rifle',
	},
	{
		id: 'autocannon',
		label: 'Autocannon',
		group_id: 'patriotic_administration_center',
		filename: 'autocannon',
	},
	{
		id: 'expendable_anti-tank',
		label: 'Expendable Anti-Tank',
		group_id: 'patriotic_administration_center',
		filename: 'expendable_anti-tank',
	},
	{
		id: 'flamethrower',
		label: 'Flamethrower',
		group_id: 'patriotic_administration_center',
		filename: 'flamethrower',
	},
	{
		id: 'machine_gun',
		label: 'Machine Gun',
		group_id: 'patriotic_administration_center',
		filename: 'machine_gun',
	},
	{
		id: 'railgun',
		label: 'Railgun',
		group_id: 'patriotic_administration_center',
		filename: 'railgun',
	},
	{
		id: 'recoilless_rifle',
		label: 'Recoilless Rifle',
		group_id: 'patriotic_administration_center',
		filename: 'recoilless_rifle',
	},
	{
		id: 'spear',
		label: 'Spear',
		group_id: 'patriotic_administration_center',
		filename: 'spear',
	},
	{
		id: 'stalwart',
		label: 'Stalwart',
		group_id: 'patriotic_administration_center',
		filename: 'stalwart',
	},
	{
		id: 'autocannon_sentry',
		label: 'Autocannon Sentry',
		group_id: 'robotics_workshop',
		filename: 'autocannon_sentry',
	},
	{
		id: 'ems_mortar_sentry',
		label: 'EMS Mortar Sentry',
		group_id: 'robotics_workshop',
		filename: 'ems_mortar_sentry',
	},
	{
		id: 'gatling_sentry',
		label: 'Gatling Sentry',
		group_id: 'robotics_workshop',
		filename: 'gatling_sentry',
	},
	{
		id: 'guard_dog',
		label: 'Guard Dog',
		group_id: 'robotics_workshop',
		filename: 'guard_dog',
	},
	{
		id: 'machine_gun_sentry',
		label: 'Machine Gun Sentry',
		group_id: 'robotics_workshop',
		filename: 'machine_gun_sentry',
	},
	{
		id: 'mortar_sentry',
		label: 'Mortar Sentry',
		group_id: 'robotics_workshop',
		filename: 'mortar_sentry',
	},
	{
		id: 'patriot_exosuit',
		label: 'Patriot Exosuit',
		group_id: 'robotics_workshop',
		filename: 'patriot_exosuit',
	},
	{
		id: 'rocket_sentry',
		label: 'Rocket Sentry',
		group_id: 'robotics_workshop',
		filename: 'rocket_sentry',
	},
]